spring.application.name=Migrations_week39
spring.datasource.url=jdbc:mysql://localhost:3306/studentdatabasechange?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=springstudent
spring.datasource.password=springstudent


# This will enable flyway, and point to the db/migration folder - where i store the SQL files.
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.password=springstudent
spring.flyway.user=springstudent
spring.flyway.url=jdbc:mysql://localhost:3306/studentdatabasechange

# This ensures JPA isn't changing the schema behind flyway (it just confirms my entity model, against the db).
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true